---
- hosts: nfx250-S1-TWO
  gather_facts: false
  tasks:

  - name: wget of ubuntu cloudimage to nfx250
    shell: wget -nc http://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.vmdk
    args:
      chdir: /var/third-party/images

  - name: expand cloudimage to local qcow2
    shell: qemu-img convert -f vmdk -O qcow2 xenial-server-cloudimg-amd64-disk1.vmdk xenial-server-cloudimg-amd64-disk1.qcow2
    args:
      chdir: /var/third-party/images

  - name: create image workcopy
    shell: cp xenial-server-cloudimg-amd64-disk1.qcow2 generic.qcow2
    args:
      chdir: /var/third-party/images

  - name: create iso directory
    file:
      path: /var/third-party/iso
      state: directory

  - name: delete multiple files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /var/third-party/iso/meta-data
      - /var/third-party/iso/user-data
      - /var/third-party/iso/generic.iso

  - name: copy meta-data file over to nfx
    copy: src=meta-data dest=/var/third-party/iso/meta-data owner=root group=root mode=0666

  - name: copy user-data file over to nfx
    copy: src=user-data dest=/var/third-party/iso/user-data owner=root group=root mode=0666

  - name: create bootiso
    shell: genisoimage -output generic.iso -volid cidata -joliet -rock user-data meta-data
    args:
      chdir: /var/third-party/iso
