---
- hosts:
    - nfx250-S2-JDM3
  roles:
    - role: '{{playbook_dir}}'
  gather_facts: false
  vars:
  #  vm_name: "newubuntu1"
    target_dir: "/var/third-party/iso/"

  tasks:
  - name: create iso directory
    file:
      path: /var/third-party/iso
      state: directory

  - name: delete multiple files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "{{ target_dir }}/{{ vm_name }}_meta-data"
      - "{{ target_dir }}/{{ vm_name }}_user-data"
      - "{{ target_dir }}/{{ vm_name }}.iso"
      - "{{ target_dir }}/{{ vm_name }}_create.conf"
      - "{{ target_dir }}/{{ vm_name }}_delete.conf"

  - name: copy file meta-data
    template:
      src:  "{{playbook_dir}}/meta-data"
      dest: "{{ target_dir }}/{{ vm_name }}_meta-data"

  - name: replace vm_name in in meta-data file
    replace:
      path: "{{ target_dir }}/{{ vm_name }}_meta-data"
      regexp: "generic"
      replace: "{{ vm_name }}"
      backup: no

  - name: copy file user-data
    template:
      src:  "{{playbook_dir}}/user-data"
      dest: "{{ target_dir }}/{{ vm_name }}_user-data"

  - name: replace vm_name in in user-data file
    replace:
      path: "{{ target_dir }}/{{ vm_name }}_user-data"
      regexp: "generic"
      replace: "{{ vm_name }}"
      backup: no

  - name: create bootiso
    shell: genisoimage -output "{{ vm_name }}.iso" -volid cidata -joliet -rock "{{ vm_name }}_meta-data" "{{ vm_name }}_user-data"
    args:
      chdir: "{{ target_dir }}"
