---
- hosts:
    - nfx250-S2-JDM3
  roles:
    - role: '{{playbook_dir}}'
  connection: local
  gather_facts: no
  vars:
    target_dir: "/var/third-party/iso/"

  tasks:
  - name: create configuration directory
    file:
      path: "{{ target_dir }}"
      state: directory

  - name: delete file
    file:
      path: "{{ target_dir }}/{{ vm_name }}_create.conf"
      state: absent

  - name: copy template of VNF with multiple interfaces
    template:
      src:    "{{ playbook_dir }}/dynamic_variable_prepare_jdm_set_config_with_jinja.j2"
      dest:   "{{ target_dir }}/{{ vm_name }}_create.conf"
      force:  yes
      backup: no
